### ISSUE TITLE
Event Completion Trigger always times out

### ISSUE THREAD

**Issue by danielwestendorf** [westy92/html-pdf-chrome#137]
I'm having trouble getting completion triggers working. What I think was working with a previous release is no longer working for me.

html-pdf-chrome version: 0.5.0

```javascript
const htmlPdf = require('html-pdf-chrome');
const html = '<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> </head> <body> <h1 id="title">Event completion trigger test</h1> <script type="text/javascript"> let title = document.getElementById("title"); title.dispatchEvent(new CustomEvent("pdfRenderReady", {})); </script> </body> </html>'

const options = { 
  completionTrigger: new htmlPdf.CompletionTrigger.Event('pdfRenderReady', '#title', 2000) 
}

htmlPdf.create(html, options).then((pdf) => pdf.toFile('test.pdf'));
```

This results in:

```javascript
> htmlPdf.create(html, options2).then((pdf) => pdf.toFile('test.pdf'));
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> (node:21385) UnhandledPromiseRejectionWarning: Error: CompletionTrigger timed out.
    at /Users/dwestendorf/Repos/pdf-bot-pro/node_modules/html-pdf-chrome/lib/src/index.js:155:23
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dwestendorf/Repos/pdf-bot-pro/node_modules/html-pdf-chrome/lib/src/index.js:4:58)
    at <anonymous>
(node:21385) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

What is my malfunction?

**Comment by danielwestendorf** [comment]
Womp! The trigger was firing before the page was fully loaded. This html works as expected.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <h1 id="title">Event completion trigger test</h1>
    <script type="text/javascript">
      setTimeout(function() {
        let title = document.getElementById("title");

        title.dispatchEvent(new CustomEvent("pdfRenderReady", {}));
      }, 500)
    </script>
  </body>
</html>
```

**Comment by danielwestendorf** [comment]
Un-womp. 

It seems that event completion triggers only works after some arbitrary point in time, I assume after the page navigation has completed. If the JS has completed before that, then the event is never received. 

I tried firing my event after the `load` event was received on the window, and this was too soon. I have to add an arbitrary timeout, or repeatedly fire the the event to get the completion trigger to fire.

My use case is that I have browser-side JavaScript which sometimes takes a long time to evaluate, and at other times is really quick, depending on the data being rendered. I was hoping to use a single event to indicate that the load is complete.

**Comment by westy92** [comment]
I'll look into attaching an event listener before the page load. Thanks for the info!

**Comment by danielwestendorf** [comment]
FWIW, it may just make more sense to eliminate events as a completion trigger and encourage variable or element triggers.

**Comment by 630348568** [comment]
I also found this problem. How do I deal with it?
