### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by vaibhav15s** [westy92/html-pdf-chrome#140]
Hi
I used the javascript example and run node test.js. But I am getting this error, please let me know what I am missing.
~/node_modules/html-pdf-chrome/lib/src/index.js:75
            const { Page } = client;
                  ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/svaibhav/node_modules/html-pdf-chrome/test.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by vaibhav15s** [comment]
I tried in Windows but getting this error:

ERROR: The process with PID 29396 (child process of PID 31328) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 27576 (child process of PID 23168) could not be terminated.
Reason: The operation attempted is not supported.

**Comment by vaibhav15s** [comment]
Sorry I was using nodejs 4.9. With new nodejs it works fine.

**Comment by westy92** [comment]
html-pdf-chrome requires a minimum Node.js version of 6.
Node.js 4.x is end-of-lifed this month! https://github.com/nodejs/Release
